# Task 1 - Install Node
# Task 2 - Yarn Build
# Task 3 - Zip up Build Files
# Task 4 - Publish Artifact
# Task 5 - Copy files to Server over SSH


trigger:
- master

variables:
    buildMonth: $[format('{0:MM}', pipeline.startTime)]
    buildDay: $[format('{0:dd}', pipeline.startTime)]


pool:
  vmImage: ubuntu-latest

stages:
- stage: Build_Client
  displayName: Build Client
  jobs:
  - job: Build_Client
    displayName: Build Client

    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '16.x'
      displayName: 'Install Node.js'

    - script: |
        yarn install
        yarn run build
      displayName: 'yarn install and build'

    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: 'build/'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/pw-$(buildMonth)-$(buildDay).zip'
        replaceExistingArchive: true
        verbose: true

    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: $(Build.ArtifactStagingDirectory)
        artifactName: YarnBuild_$(buildMonth)_$(buildDay)

    - task: CopyFilesOverSSH@0
      displayName: 'Securely copy files to the remote machine'
      inputs:
        sshEndpoint: timoserver
        SourceFolder: '$(Build.ArtifactStagingDirectory)'
        Contents: '**'
        targetFolder: /home/kmcode/scm-km/test/
        failOnEmptySource: true