# Kunal Menon Pipeline for Build and Deploy to Timos Server
# This 1st builds the JAR file for the server 
# Then 2nd builds the build files for the client
# Final step copies the JAR file and BUILD folder to the server over SSH

trigger:
- master

pool:
  vmImage: ubuntu-latest


stages:
- stage: Build_Server
  displayName: Build Server
  jobs:
  - job: Build_Server
    displayName: Build SCM Server
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'scm-server/pom.xml'
        mavenOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.9'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        goals: 'package'
    - task: CopyFiles@2
      displayName: 'Copy Files to artifact staging directory'
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: '**/target/*.?(war|jar)'
        TargetFolder: $(Build.ArtifactStagingDirectory)
    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: $(Build.ArtifactStagingDirectory)
        artifactName: SpringBootBuild

- stage: Build_Clicent
  displayName: Build Client
  jobs:
  - job: Build_Client
    displayName: Build SCM Client

    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '16.x'
      displayName: 'Install Node.js'

    - script: |
        cd scm-client
        npm install
        npm run build
      displayName: 'npm install and build'
    - task: CopyFiles@2
      displayName: 'Copy Files to artifact staging directory'
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: '**/build/**'
        TargetFolder: $(Build.ArtifactStagingDirectory)
    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: $(Build.ArtifactStagingDirectory)
        artifactName: ReactBuild

- stage: Copy_to_Timos_Server
  displayName: Copy Build to Timos Server
  jobs:
  - job: Copy_to_Timos_Server
    displayName: Copy Build to Timos Server
    steps:
    - task: CopyFilesOverSSH@0
      displayName: 'Securely copy files to the remote machine'
      inputs:
        sshEndpoint: timoserver
        contents: |
          SpringBootBuild/**
          ReactBuild/**
        sourceFolder: '$(Build.ArtifactStagingDirectory)'
        targetFolder: /home/kmcode/scm-km/test/
        cleanTargetFolder: true
        failOnEmptySource: true