# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build_Server
  displayName: Build Server Image
  jobs:
  - job: Build_Server
    displayName: Build Server
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '**/scm-server/serverDockerFile'
        tags: |
          $(tag)
- stage: Build_Client
  displayName: Build Client Image
  jobs:
  - job: Build_Client
    displayName: Build Client
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '**/scm-client/clientDockerFile'
        tags: |
          $(tag)          
